### ISSUE TITLE
Upload file, json message on screen

### ISSUE THREAD

**Issue by enridaga** [spice-h2020/linked-data-hub#32] opened 2021-12-23 12:28 UTC
In my development environment, when I try to upload a file, I get the message below. The file is correctly uploaded.

![Screenshot 2021-12-23 at 12 27 13](https://user-images.githubusercontent.com/642064/147240565-bfa0b5c0-d4f0-4922-b0f8-e7d23ebc3653.png)

**Comment by JaseMK** [comment] 2022-01-05 10:22
I believe this is now fixed in v0.9.2 of mkdf/mkdf-file
https://github.com/mkdf/mkdf-file/commit/8b28f7a3512a4bb58414269003925198799e1f92

There was an incorrect echo statement of the JSON response fromt he file upload which has now been removed. I'm almost certain this was the cause of the problem, however for some reason I was not seeing this error on my development build (or the production version), so cannot 100% confirm the issue has been resolved.

**Closed as completed** 2022-02-02 12:16 UTC
